### ISSUE TITLE
Projektbericht

### ISSUE THREAD

**Issue by YuriDevAT** [YuriDevAT/accessibility-in-DH#24]
Schreibe einen ca. 7 seitigen (Fließtext) Projektbericht, der folgende Kriterien erfüllt:

- [x] Abstract zum Project, max. 400 Wörter
- [x] Projektbeschreibung ca 1 Seite
- [x] Beschreibung der Daten
- [x] Datenspeicherungsstrategie (Datenmodelle, EERM, welche Tools werden verwendet, etc
- [x] Mock Ups
- [x] Zusätzliches
- [x] Reflexion/Erfahrungen mit der Projektarbeit (individuell)
- [x] Kennzeichnen, wer was geschrieben hat

Mehr Details im [Original Dokument der LV](https://github.com/YuriDevAT/accessibility-in-DH/blob/main/project_presentation_final_part.pdf).

**Comment by EmiliaAnnaG** [comment]
There you go: 
https://docs.google.com/document/d/19OtBdccEdMugjzT27VcQbXKxmv5UmEBGvCiZN2tGxbQ/edit?usp=sharing

**Comment by YuriDevAT** [comment]
@EmiliaAnnaG @lug-robin Ich wäre fertig mit meinem Teil des Berichts. Falls ich zu viel geschrieben habe und jemand hat das Gefühl er bräuchte mehr, kann gerne der Name hinzugefügt werden, oder wir lassen es einfach komplett weg und geben an es war 33,33333333333 von uns allen (was mir sehr recht wäre).

Wenn Text vor meinem Text hinzukommt, kann es sein, dass sich die Bilder im Abschnitt von Mock Ups verschiebt. Bitte das nochmal anschauen, bevor es abgeschickt wird.

Einstellung ist: Calibri, 1.5 Zeilenabstand, Schriftgröße 12 bei Fließtext.

**Comment by lug-robin** [comment]
i will get to it this weekend. bin grad auf ner tagung, kann aber versuchen uns in eine bessere note reinzuschleimen, weil markus auch da ist :p

**Comment by lug-robin** [comment]
ich hab vielleicht gehört, dass bestimmte personen(gruppen) finden, dass dh viel zu gute noten einträgt und sich das ändern sollte

**Comment by EmiliaAnnaG** [comment]
Habe den Text in einer Vorlage übertragen damit's bissi hübscher designt ist ^^
https://docs.google.com/document/d/1hzMCmtIXQlmW4F_BrWhiKSIxPuP9TCn3oTcP_DJg4pQ/edit?usp=sharing
