### ISSUE TITLE
Create Project Presentation

### ISSUE THREAD

**Issue by YuriDevAT** [YuriDevAT/accessibility-in-DH#7]
As written in the [project presentation part 1 guidelines](https://github.com/YuriDevAT/accessibility-in-DH/blob/main/project_presentation_part_1.pdf) a presentation has to be created to show of the interim status of the project.

**Following questions should be answered:**

- [x] What are the goals of this project
- [x] Who are the intended users? What should they be able to do?
- [x] With which data will be worked?
- [x] How should the finished product look like and what should it do? (Website, App, Tool, ...)
- [x] Are there any modelling already? (semantic/formal data model, EER data model, ...) If yes, how do they look like?

Finishing this issue is required to start with [issue No8](https://github.com/YuriDevAT/accessibility-in-DH/issues/8).

**Comment by EmiliaAnnaG** [comment]
Started to work on the presentation here 
https://docs.google.com/presentation/d/18tH6Yz44D5h-X9T19QRSU_PwjBBmv1SEFD4lyNCoQQ8/edit?usp=sharing

So far the first 3 points are filled out. We can discuss tomorrow if there is something you want to add and what to write for the remaining 2
- [ ]  What are the goals of this project
- [ ]  Who are the intended users? What should they be able to do?
- [ ]  With which data will be worked?
- [ ] How should the finished product look like and what should it do? (Website, App, Tool, ...)
- [ ] Are there any modelling already? (semantic/formal data model, EER data model, ...) If yes, how do they look like?

**Comment by YuriDevAT** [comment]
Perfect @EmiliaAnnaG 😎 We are definitely good in time.

**Comment by lug-robin** [comment]
Schaut mega nice aus!! ich würd namen und websiten noch alphabetisch ordnen und arbeite auch schon an ersten modellierungen angelehnt an der webaim website. also kurz gesagt, ich hab ein bar plot und sobald alle daten in einen dokument sind, kann das auch auf alles angewendet werden.

aber ich find auf jeden fall, dass wir mega schnell in der zeit sind !

**Comment by lug-robin** [comment]
New To Dos: 
[ ] Design Wireframe (Julia)
[ ] Write Wireframe texts (Emilia)
[ ] EER Model (Robin)
[ ] Projektaufbau (Julia)
[ ] Other plots (Robin)
[ ] Finish presentation design (Robin)
[ ] Record (Julia)
[ ] Record (Emilia)
[ ] Record (Robin)
